# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [9]:
print(np.__version__)
print(np.show_config())

1.15.0
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    define_macros = [('HAVE_CBLAS', None)]
    libraries = ['openblas']
    language = f77
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    define_macros = [('HAVE_CBLAS', None)]
    libraries = ['openblas']
    language = f77
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    define_macros = [('HAVE_CBLAS', None)]
    libraries = ['openblas']
    language = f77
blis_info:
  NOT AVAILABLE
lapack_mkl_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    define_macros = [('HAVE_CBLAS', None)]
    libraries = ['openblas']
    language = f77
blas_mkl_info:
  NOT AVAILABLE
None


#### 3. Create a null vector of size 10 (★☆☆)

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [16]:
print(np.zeros(10).size)
print(np.zeros(10).itemsize)

10
8


size returns the amount if elements in the array

itemsize returns the bytesize of the elements, 8 means 8 bytes (type is float64, that is, 64 bits float or 8 bytes)

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [19]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [36]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [42]:
np.arange(10, 50, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [55]:
vector = [1,2,3,4]
vector[::-1]

[4, 3, 2, 1]

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [57]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [61]:
a = [1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [63]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [73]:
z = np.random.random(27).reshape(3,3,3)
# or
alt_z = np.random.random((3,3,3))
print(z)
print('==')
print(alt_z)

[[[0.35186815 0.37888778 0.98955481]
  [0.8145873  0.46607736 0.9939646 ]
  [0.96767044 0.33178378 0.01341138]]

 [[0.8939039  0.22798896 0.44710356]
  [0.58515518 0.68762252 0.98492492]
  [0.71395759 0.72022168 0.38577045]]

 [[0.07568784 0.22756474 0.65557328]
  [0.00788163 0.87580702 0.22217387]
  [0.38961861 0.4292453  0.61621164]]]
==
[[[0.38585516 0.80748545 0.04215898]
  [0.69986618 0.92237903 0.85553268]
  [0.95873703 0.04311637 0.08771713]]

 [[0.02663402 0.27544983 0.67244075]
  [0.48423193 0.57213925 0.29940928]
  [0.11632465 0.55805428 0.65928548]]

 [[0.82821302 0.34840964 0.25057969]
  [0.00945658 0.13915405 0.94219458]
  [0.38699528 0.07657125 0.16611059]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [74]:
z = np.random.random((10,10))
max = z.max()
min = z.min()
print(z, max, min)

[[6.16798338e-01 2.27504723e-01 8.62832211e-01 5.97506711e-01
  1.23479831e-01 5.76255052e-01 7.94206351e-01 8.14212534e-01
  6.30690124e-02 3.90450690e-01]
 [1.19510387e-03 8.88700094e-01 8.03664138e-01 3.38777280e-01
  7.92071441e-01 3.49464474e-01 8.35716402e-01 4.68487410e-01
  8.17167266e-01 6.50100309e-01]
 [6.68015087e-01 6.81114887e-01 9.75346610e-01 3.29825420e-01
  7.58805408e-04 2.46914209e-01 8.83982149e-01 5.09962436e-01
  8.13026102e-01 2.77084416e-01]
 [7.32115557e-01 6.99649526e-01 2.73479961e-01 6.21740396e-01
  1.46858334e-01 9.58317780e-02 8.50938002e-01 4.43314077e-01
  7.50623644e-01 1.93851642e-01]
 [8.56160480e-02 5.50611293e-01 3.37629459e-01 9.61551577e-01
  6.79764549e-01 2.21313902e-01 4.30475670e-01 7.28323822e-01
  8.24439770e-01 4.80863263e-02]
 [9.90374676e-01 2.86105302e-01 5.41214601e-01 3.98862803e-01
  6.42633191e-01 4.76283632e-01 5.51994071e-02 5.42474645e-01
  8.24981860e-02 6.38358335e-01]
 [7.95894006e-01 1.84588758e-01 6.51964627e-01 1.50647816e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [75]:
z = np.random.random(30)
print(z, z.mean())

[0.43029395 0.34921394 0.89588261 0.09082548 0.82916315 0.97833423
 0.62111082 0.90161567 0.89031465 0.69741307 0.46467137 0.57468789
 0.87711343 0.77699083 0.10141485 0.06332517 0.05890564 0.3545516
 0.90695832 0.12073567 0.78189989 0.16481219 0.94608047 0.87370428
 0.1122202  0.35798436 0.63946701 0.41251902 0.63328279 0.70554283] 0.5537011789392546


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [97]:
z = np.ones((5,5))
# z[1:-1] this selects all rows except first and last
# use it on the second position to do the same to each row selected
z[1:-1, 1:-1] = 0
print(z)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [121]:
# one dimension
z = np.ones(5)
z_padded = np.pad(z, 1, mode='constant')
print(z_padded)
print('---')
z2 = np.ones((3,3))
z_padded = np.pad(z2, 1, mode='constant')
print(z_padded)

[0. 1. 1. 1. 1. 1. 0.]
---
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [123]:
0 * np.nan

nan

In [124]:
np.nan == np.nan

False

In [127]:
np.inf > np.nan

False

In [126]:
np.nan - np.nan

nan

In [153]:
0.3 == 3 * 0.1

False

In [158]:
print('{0:.24f}'.format(0.3))
print('{0:.24f}'.format(0.1))
print('{0:.24f}'.format(3))
#floats are an aproximation :)

0.299999999999999988897770
0.100000000000000005551115
3.000000000000000000000000


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [151]:
z = np.diag(1+np.arange(4), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [132]:
np.info(np.diag)

 diag(v, k=0)

Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal array.

See Also
--------
diagonal : Return specified diagonals.
diagflat : Create a 2-D array with the flattened input as a diagonal.
trace : Sum along diagonals.
triu : Upper triangle of an array.
tril : Lower triangle of an array.

Examples
--------
>>> x = np.ar

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [190]:
# https://docs.python.org/release/2.3.5/whatsnew/section-slices.html
z = np.random.random(6)
print(z)
print(z[1::2]) # this extracts every second element (nothing for the first argument, nothing for the second, and jump by 2)
print('---')
z = np.ones(6)
z[::2] = 0
print(z)
print('---')
z = np.ones((8,8))
z[::1, ::2] = 0
print(z)
print('---')
z[::1, 1::1] = 1
print(z)
print('---')
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[0.13064052 0.20477894 0.88246175 0.76814357 0.58926764 0.19501939]
[0.20477894 0.76814357 0.19501939]
---
[0. 1. 0. 1. 0. 1.]
---
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
---
[[0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]
---
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [207]:
z = np.arange(9).reshape(3,3)
print(z)
np.unravel_index(3, (3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


(1, 0)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [218]:
a = np.array(([0, 1], [1,0]), dtype='int')
checkerboard = np.tile(a, (4,4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [225]:
z = np.random.random((5,5))
print(z)
z_norm = (z - z.min()) / (z.max() - z.min())
print(z_norm)
z_min = z.min()
z_max = z.max()
z_norm_ = (z - z_min) / (z_max - z_min)
print(z_norm_)

[[0.98795077 0.12431964 0.33068287 0.18801142 0.52647985]
 [0.18937509 0.48704201 0.78841825 0.45823128 0.30427244]
 [0.15260181 0.22504867 0.86018147 0.4700735  0.16447117]
 [0.93729002 0.17496127 0.81223433 0.71531817 0.75305739]
 [0.48935238 0.17081844 0.50361124 0.01629372 0.27547014]]
[[1.         0.111177   0.32355979 0.17672665 0.52506811]
 [0.17813011 0.48447988 0.79464718 0.45482874 0.29637897]
 [0.14028415 0.21484426 0.8685037  0.46701641 0.15249974]
 [0.94786149 0.16329584 0.81915796 0.71941478 0.75825485]
 [0.48685764 0.15903216 0.50153242 0.         0.26673652]]
[[1.         0.111177   0.32355979 0.17672665 0.52506811]
 [0.17813011 0.48447988 0.79464718 0.45482874 0.29637897]
 [0.14028415 0.21484426 0.8685037  0.46701641 0.15249974]
 [0.94786149 0.16329584 0.81915796 0.71941478 0.75825485]
 [0.48685764 0.15903216 0.50153242 0.         0.26673652]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [226]:
np.info(np.dtype)

 dtype()

dtype(obj, align=False, copy=False)

Create a data type object.

A numpy array is homogeneous, and contains elements described by a
dtype object. A dtype object can be constructed from different
combinations of fundamental numeric types.

Parameters
----------
obj
    Object to be converted to a data type object.
align : bool, optional
    Add padding to the fields to match what a C compiler would output
    for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
    or a comma-separated string. If a struct dtype is being created,
    this also sets a sticky alignment flag ``isalignedstruct``.
copy : bool, optional
    Make a new copy of the data-type object. If ``False``, the result
    may just be a reference to a built-in data-type object.

See also
--------
result_type

Examples
--------
Using array-scalar type:

>>> np.dtype(np.int16)
dtype('int16')

Structured type, one field name 'f1', containing int16:

>>> np.dtype([('f1', np.int16)])
dtype([('f1', '<i2

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)